version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin install --batch ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports:
      - '5601:5601'
    depends_on:
      - 'elasticsearch'

  trino:
    image: 'docker.io/trinodb/trino:latest'
    container_name: trino
    ports:
      - '8088:8088'
    volumes:
      - ./trino:/etc/trino
      - ./trino/data:/data/trino
