---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "word-analyzer.fullname" . }}
  labels:
    {{- include "word-analyzer.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: tcp-8080
      scheme: http
  selector:
    matchLabels:
    {{- include "word-analyzer.labels" . | nindent 6 }}
